"""Parity fixture generated by ZipStrain's Python profiler."""

from importlib.metadata import entry_points
from pathlib import Path

import polars as pl
import pyarrow.parquet as pq
import pytest

from zipstrain.profile_backends import ProfileRequest, run_profile


DATA = Path(__file__).parent / "data"


@pytest.mark.skipif(
    not entry_points(group="zipstrain.profile_backends", name="rust_profiler"),
    reason="The compiled Rust plugin wheel is not installed",
)
def test_installed_backend_matches_python_fixture(tmp_path):
    run_profile(
        ProfileRequest(
            bam_file=DATA / "small.bam",
            bed_file=DATA / "small.bed",
            stb_file=DATA / "small.stb",
            null_model=DATA / "null_model.parquet",
            gene_range_table=DATA / "genes.tsv",
            output_dir=tmp_path,
            num_chunks=8,
            max_concurrency=4,
            min_read_ani=0.0,
            read_inclusion="all-mapped",
        ),
        "rust_profiler",
    )

    name = "small_profile.parquet"
    actual = pq.ParquetFile(tmp_path / name)
    expected = pq.ParquetFile(DATA / "expected" / name)
    assert actual.schema_arrow.remove_metadata() == expected.schema_arrow.remove_metadata()
    assert actual.metadata.num_rows == expected.metadata.num_rows == 9982
    for key in (
        b"zipstrain_sorted_by",
        b"zipstrain_reference_hash",
        b"zipstrain_gene_hash",
        b"zipstrain_null_model_hash",
        b"zipstrain_stb_hash",
    ):
        assert actual.metadata.metadata.get(key) == expected.metadata.metadata.get(key)
    assert actual.read().equals(expected.read())

    for suffix, keys in (("gene_stats", ["genome", "gene"]), ("genome_stats", ["genome"])):
        name = f"small_{suffix}.parquet"
        got = pl.read_parquet(tmp_path / name).sort(keys)
        want = pl.read_parquet(DATA / "expected" / name).sort(keys)
        assert got.columns == want.columns
        assert got.shape == want.shape
        for actual_row, expected_row in zip(got.iter_rows(named=True), want.iter_rows(named=True)):
            for column, expected_value in expected_row.items():
                actual_value = actual_row[column]
                if isinstance(expected_value, float):
                    assert actual_value == pytest.approx(expected_value, rel=1e-10, abs=1e-10)
                else:
                    assert actual_value == expected_value
