FROM continuumio/miniconda3

ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu
ARG SRA_TOOLKIT_VERSION=3.2.0
ARG ZIPSTRAIN_PROJECT_DIR=/opt/zipstrain

ENV PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /opt

RUN printf '%s\n' \
        'channels:' \
        '  - conda-forge' \
        '  - bioconda' \
        'channel_priority: strict' \
    > /root/.condarc

RUN conda install -y \
        python=3.12 \
        pip \
        parallel \
        pigz \
        wget \
        samtools \
        bowtie2 \
        prodigal \
        sylph \
    && conda clean -afy

COPY zipstrain ${ZIPSTRAIN_PROJECT_DIR}

RUN python -m pip install --upgrade pip setuptools wheel \
    && python -m pip install "torch>=2.6,<3.0.0" --index-url ${TORCH_INDEX_URL} \
    && python -m pip install "polars[rtcompat]" \
    && python -m pip install "${ZIPSTRAIN_PROJECT_DIR}[matrix]" \
    && python -m pip install loguru \
    && wget --output-document sratoolkit.tar.gz "https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/${SRA_TOOLKIT_VERSION}/sratoolkit.${SRA_TOOLKIT_VERSION}-ubuntu64.tar.gz" \
    && tar -xzf sratoolkit.tar.gz \
    && rm -f sratoolkit.tar.gz

ENV PATH="/opt/sratoolkit.${SRA_TOOLKIT_VERSION}-ubuntu64/bin:${PATH}"
