FROM continuumio/miniconda3
RUN conda config --add channels conda-forge
RUN conda install -y parallel
RUN conda install -y -c bioconda samtools
RUN conda install -y -c bioconda bowtie2
RUN conda install -y -c bioconda prodigal
RUN conda install -y -c bioconda sylph
RUN pip install pyarrow
ADD zipstrain /zipstrain
RUN pip install /zipstrain
RUN pip install loguru
RUN wget --output-document sratoolkit.tar.gz https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.2.0/sratoolkit.3.2.0-ubuntu64.tar.gz && \
    tar -xzf sratoolkit.tar.gz && \
    rm sratoolkit.tar.gz
ENV PATH="/sratoolkit.3.2.0-ubuntu64/bin:${PATH}"
RUN pip install polars[rtcompat]